### ISSUE TITLE
Onclick java script link open

### ISSUE THREAD

**Issue by Mike-Mooler** [martinsbalodis/web-scraper-chrome-extension#200] opened 2017-04-19 06:26 UTC
Hi,
When links are with java script OnClink attribute, There is no way to capture and open these links.
Please add this feature.

Example:
```
<li class="dummyClass" onclick="javascript:window.location.href='/scwar/scr/Partner/SC2PP.html';">
	<a href="javascript:void(0);">
		<div class="partner-info">
			<span>MyCol</span><p>LA,CAE</p>
		</div>
	</a>
</li>
```

**Comment by martinsbalodis** [comment] 2017-12-07 10:23
Duplicate of #86

**Closed by martinsbalodis** 2017-12-07 10:23 UTC
