### ISSUE TITLE
Get new page url

### ISSUE THREAD

**Issue by navneetgarggate6** [martinsbalodis/web-scraper-chrome-extension#205] opened 2017-05-24 14:13 UTC
Is this possible to get click on a button and a new page or tab open then capture that new page/tab url ?

Also go to back functionality?

**Comment by jwillmer** [comment] 2017-05-29 10:53
- To get a link you use the link element
- Why should you need to go back? If you need to loop through many links then select many.

Please play around with the tool first before asking.

**Comment by navneetgarggate6** [comment] 2017-05-30 04:36
Actually i want to fetch a detail which is on new page and when i go to new page parent element not available on that new page so my crawling stop and no data fetched.

**Comment by jwillmer** [comment] 2017-05-30 06:29
Please share the sitemap so we can have a look and maybe help you out.

**Comment by navneetgarggate6** [comment] 2017-05-30 06:42
http://www.grabon.in/free-samples-india/


{"_id":"grabon","startUrl":"http://www.grabon.in/free-samples-india/","selectors":[{"parentSelectors":["_root"],"type":"SelectorElement","multiple":true,"id":"Main","selector":"article.sm-coupon","delay":""},{"parentSelectors":["Main"],"type":"SelectorText","multiple":false,"id":"Title","selector":"h3.smci-h","regex":"","delay":""},{"parentSelectors":["Main"],"type":"SelectorText","multiple":false,"id":"Description","selector":"div.smci-desp","regex":"","delay":""},{"parentSelectors":["Main"],"type":"SelectorText","multiple":false,"id":"Content","selector":"div.smci-tip","regex":"","delay":""},{"parentSelectors":["Main"],"type":"SelectorImage","multiple":false,"id":"Image","selector":"img.smci-img","downloadImage":false,"delay":""}]}

I want to grab active offer link and coupon code

**Comment by jwillmer** [comment] 2017-05-30 15:10
For me your sitemap works. I get all 4 columns `Title, Desc., Content, Img`

**Comment by navneetgarggate6** [comment] 2017-05-30 16:06
Yes but I want to fetch the URL as well on click on offer links

**Comment by jwillmer** [comment] 2017-05-31 06:32
Please be more specific, this is what your sitemap is returning me:

 | Title |	Description  |	Content	| Image-src | 
|----------|:-------------:|------:|------:|
 | Free Sample Of Dabur Vatika Olive Oil for your Dream Hair wish!	 | Get your free sample of Dabur vatika olive hair oil today and make your dream hair wish come true. So go on,share your hair wish with Dabur vatika and stand a chance to win a Free sample of the all-new Dabur Enriched Olive Hair Oil, with compliments! No coupon code required.  | 	Tags: Beauty It's A Promotional Offer & Availability Of Freebies Is Completely Under Merchants Discretion.	 | http://cdn.lmitassets.com/gograbon/images/coupon/1917-24716-1464367352007 |

**Comment by navneetgarggate6** [comment] 2017-05-31 06:37
I want to get the url of the offer. When you click on the ACTIVATE OFFER button it redirect to a new page i need that link 
![image](https://cloud.githubusercontent.com/assets/16791876/26618839/6fcbdd00-45f9-11e7-8627-2f4f70cfbad1.png)

This button open a new tab and open offer page and also redirect old tab to new page. I want to grab this below offer link.


https://www.mybeautynaturally.com/vatikaolive/pages/wish.html?utm_source=grabon&utm_medium=grabon&utm_campaign=sample

**Comment by jwillmer** [comment] 2017-05-31 07:05
As it looks like they build the link dynamically with JavaScript together. You can basically go through there source code to get to know how they do it and do the same.
This page is designed to prevent web scraping by using such methods. I am afraid this tool is not advanced enough to circumvent there protection out of the box.

**Comment by navneetgarggate6** [comment] 2017-05-31 07:08
Ok, thanks for your help.

**Comment by martinsbalodis** [comment] 2017-12-07 10:23
Duplicate of #86

**Closed by martinsbalodis** 2017-12-07 10:23 UTC
