### ISSUE TITLE
Multiple URL Feature to Permit Copy and Paste from Large Spreadsheets?

### ISSUE THREAD

**Issue by UYScutti** [martinsbalodis/web-scraper-chrome-extension#233] opened 2017-10-17 20:51 UTC
When you select a sitemap, and go to Edit Metadata, can a feature be added to copy and paste a lot of URLs from a single spreadsheet column into the metadata URLs in Webscraper.io?  I know you can press the + button to add another entry, but I'm thinking that this would make it easier for a lot of users like myself.

**Comment by martinsbalodis** [comment] 2017-12-07 09:57
Duplicate of #86 The site is sending a post request and then reloading the page.

**Closed by martinsbalodis** 2017-12-07 09:57 UTC
